[package]
name = "redindelible-github-io"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1.0.6"
askama = "0.12.1"
once_cell = "1.18.0"
regex = "1.10.2"
serde_json = "1.0.107"
chrono = "0.4.31"
typed-arena = "2.0.2"